services:
  db:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_SENHA}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    container_name: ${DB_NOME_CONTAINER}
  front:
    build:
      context: ./front
      dockerfile: front.dockerfile
      target: prod
      args:
        PORT: ${FRONT_PORT}
    image: ${FRONT_NOME_IMAGEM}
    container_name: ${FRONT_NOME_CONTAINER}
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    environment:
      PORT: ${FRONT_PORT}
volumes:
  pgdata: