services:
  db:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_SENHA}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init_scripts:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT}:${DB_PORT}"
    container_name: ${DB_NOME_CONTAINER}
  front:
    build:
      context: ./front
      dockerfile: front.dockerfile
      target: dev
    depends_on:
      - back
    image: ${FRONT_NOME_IMAGEM}
    container_name: ${FRONT_NOME_CONTAINER}
    ports:
      - "${FRONT_PORT}:3000"
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NEXT_PUBLIC_BACK_URL: "http://back:5000"
  back:
    build:
      context: ./back
      dockerfile: back.dockerfile
      target: dev
    depends_on:
      - db
    image: ${BACK_NOME_IMAGEM}
    container_name: ${BACK_NOME_CONTAINER}
    ports:
      - "${BACK_PORT}:5000"
    volumes:
      - ./back:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DB_URL: "postgresql://postgres:${DB_SENHA}@db:5432/${DB_BANCO}"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      FRONT_URL: "http://localhost:${FRONT_PORT}"

volumes:
  pgdata: