services:
  db:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_SENHA}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init_scripts:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT}:${DB_PORT}"
    container_name: ${DB_NOME_CONTAINER}
  front:
    build:
      context: ./front
      dockerfile: front.dockerfile
      target: dev
    image: ${FRONT_NOME_IMAGEM}
    container_name: ${FRONT_NOME_CONTAINER}
    ports:
      - "${FRONT_PORT}:3000"
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules
volumes:
  pgdata: